### ISSUE TITLE
No stable connection to heltec wireless stick lite v3

### ISSUE THREAD

**Issue by qbak** [TheCommsChannel/TC2-BBS-mesh#101]
Hi,
I have tried to connect BBS to heltec wireless stick lite v3 via TCP and Serial from rpi 2B. Meshtastic device is using fresh [Meshtastic Firmware 2.5.14](https://github.com/meshtastic/firmware/releases/tag/v2.5.14.f2ee0df).
I changed 3 different power supplies as suggested on the internet for dropping the serial on rpi due to undervoltage.
I have either 'python3[842]: meshtastic.mesh_interface.MeshInterface.MeshInterfaceError: Timed out waiting for connection completion' or some type of decoding errors ex. 
'Dec 01 17:05:03 tc2bbs python3[834]: 2024-12-01 17:05:03 - ERROR - Error while parsing FromRadio bytes:b'"u\x08\xa8\x9f\xce\x86\x0e\x12L\n\t!e0d38fa8\x12\rSebLoRek_BAZA\x1a\x04SbBB"\x06\x08\xf9\xe0\xd3\x8f\xa8(\nB \xb2\x10\x94N\xaf`\xab\xc0WT\xf8=X\xdc\x98\x94Y\x07\xd0\xacl\xfc\xfe\xfaT\x96B\xb9\x05]"X%\x00\x00l\xc1-\x906Lg2\x13\x08e\x15\x0c\x02\x87@\x1d\xb2\xe4\x1f@\n`\x1b[34m\x00D' Truncated message.
Dec 01 17:05:03 tc2bbs python3[834]: Traceback (most recent call last):
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 1052, in _handleFromRadio
Dec 01 17:05:03 tc2bbs python3[834]:     fromRadio.ParseFromString(fromRadioBytes)
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/message.py", line 204, in ParseFromString
Dec 01 17:05:03 tc2bbs python3[834]:     return self.MergeFromString(serialized)
Dec 01 17:05:03 tc2bbs python3[834]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1183, in MergeFromString
Dec 01 17:05:03 tc2bbs python3[834]:     if self._InternalParse(serialized, 0, length) != length:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1250, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Dec 01 17:05:03 tc2bbs python3[834]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 701, in DecodeField
Dec 01 17:05:03 tc2bbs python3[834]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1250, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Dec 01 17:05:03 tc2bbs python3[834]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 701, in DecodeField
Dec 01 17:05:03 tc2bbs python3[834]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1241, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     new_pos = local_SkipField(buffer, old_pos, end, tag_bytes)
Dec 01 17:05:03 tc2bbs python3[834]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 1032, in SkipField
Dec 01 17:05:03 tc2bbs python3[834]:     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
Dec 01 17:05:03 tc2bbs python3[834]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 922, in _SkipLengthDelimited
Dec 01 17:05:03 tc2bbs python3[834]:     raise _DecodeError('Truncated message.')
Dec 01 17:05:03 tc2bbs python3[834]: google.protobuf.message.DecodeError: Truncated message.
Dec 01 17:05:03 tc2bbs python3[834]: 2024-12-01 17:05:03 - ERROR - Error while handling message from radio Truncated message.
Dec 01 17:05:03 tc2bbs python3[834]: Traceback (most recent call last):
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 193, in __reader
Dec 01 17:05:03 tc2bbs python3[834]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 1058, in _handleFromRadio
Dec 01 17:05:03 tc2bbs python3[834]:     raise ex
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 1052, in _handleFromRadio
Dec 01 17:05:03 tc2bbs python3[834]:     fromRadio.ParseFromString(fromRadioBytes)
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/message.py", line 204, in ParseFromString
Dec 01 17:05:03 tc2bbs python3[834]:     return self.MergeFromString(serialized)
Dec 01 17:05:03 tc2bbs python3[834]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1183, in MergeFromString
Dec 01 17:05:03 tc2bbs python3[834]:     if self._InternalParse(serialized, 0, length) != length:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1250, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Dec 01 17:05:03 tc2bbs python3[834]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 701, in DecodeField
Dec 01 17:05:03 tc2bbs python3[834]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1250, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Dec 01 17:05:03 tc2bbs python3[834]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 701, in DecodeField
Dec 01 17:05:03 tc2bbs python3[834]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Dec 01 17:05:03 tc2bbs python3[834]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1241, in InternalParse
Dec 01 17:05:03 tc2bbs python3[834]:     new_pos = local_SkipField(buffer, old_pos, end, tag_bytes)
Dec 01 17:05:03 tc2bbs python3[834]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 1032, in SkipField
Dec 01 17:05:03 tc2bbs python3[834]:     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
Dec 01 17:05:03 tc2bbs python3[834]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 01 17:05:03 tc2bbs python3[834]:   File "/home/pi/TC2-BBS-mesh/venv/lib/python3.11/site-packages/google/protobuf/internal/decoder.py", line 922, in _SkipLengthDelimited
Dec 01 17:05:03 tc2bbs python3[834]:     raise _DecodeError('Truncated message.')
Dec 01 17:05:03 tc2bbs python3[834]: google.protobuf.message.DecodeError: Truncated message.'

**Comment by Dphilly-215** [comment]
I had a lot of issues with my heltec using tcp and serial. I'm also running this on a pi. Moved to my tbeam via serial and no issues. I think it's a heltec specific issue.
