### ISSUE TITLE
NameError: name 'receiver_or_group' is not defined

### ISSUE THREAD

**Issue by myerika** [TheCommsChannel/TC2-BBS-mesh#103]
I got these error have I missed something?

- JS8Call - INFO - Received JS8Call message: SE0YOS: to @TC2 - TJOSAN TC2 IGEN ♢
Traceback (most recent call last):
  File "/home/pi/TC2-BBS-mesh/[server.py](javascript:void(0);)", line 93, in <module>
    main()
  File "/home/pi/TC2-BBS-mesh/[server.py](javascript:void(0);)", line 80, in main
    js8call_client.connect()
  File "/home/pi/TC2-BBS-mesh/js8call_[integration.py](javascript:void(0);)", line 206, in connect
    self.process(message)
  File "/home/pi/TC2-BBS-mesh/js8call_[integration.py](javascript:void(0);)", line 167, in process
    self.insert_message('groups', sender, receiver, msg)
  File "/home/pi/TC2-BBS-mesh/js8call_[integration.py](javascript:void(0);)", line 129, in insert_message
    ''', (sender, receiver_or_group, message))
NameError: name 'receiver_or_group' is not defined

I have group @TC2 defined in js8groups

Any tip is appreciated

**Comment by kc7hes** [comment]
From one of my Smarter than Me buddies:

For the TC2-BBS-mesh project:
in the js8call_integration.py file, change the following lines from/to:
line 129: Change:
                ''', (sender, receiver_or_group, message))
to
                ''', (sender, recipient, message))
