### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by SpeedGP** [TheCommsChannel/TC2-BBS-mesh#79]
No clue what happened, it has been sitting on my roof working for about a week, connected to a t-beam, and it just stopped responding. I've rebooted both devices, but it doesn't seem to do much. I can connect to both devices over wifi and communicate /reboot both.

Any thoughts?

user@Yes-BBS:~ $ journalctl -u mesh-bbs.service -f --no-tail
Aug 11 22:28:35 Yes-BBS systemd[1]: Started mesh-bbs.service - TC²-BBS Meshtastic Version.
Aug 11 22:29:15 Yes-BBS python3[528]: 2024-08-11 22:29:15 - ERROR - Error while handling message from radio Error parsing message
Aug 11 22:29:16 Yes-BBS python3[528]: Traceback (most recent call last):
Aug 11 22:29:16 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 173, in __reader
Aug 11 22:29:16 Yes-BBS python3[528]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
Aug 11 22:29:16 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 875, in _handleFromRadio
Aug 11 22:29:16 Yes-BBS python3[528]:     fromRadio.ParseFromString(fromRadioBytes)
Aug 11 22:29:16 Yes-BBS python3[528]: google.protobuf.message.DecodeError: Error parsing message
Aug 11 22:29:33 Yes-BBS python3[528]: ████████╗ ██████╗██████╗       ██████╗ ██████╗ ███████╗
Aug 11 22:29:33 Yes-BBS python3[528]: ╚══██╔══╝██╔════╝╚════██╗      ██╔══██╗██╔══██╗██╔════╝
Aug 11 22:29:33 Yes-BBS python3[528]:    ██║   ██║      █████╔╝█████╗██████╔╝██████╔╝███████╗
Aug 11 22:29:33 Yes-BBS python3[528]:    ██║   ██║     ██╔═══╝ ╚════╝██╔══██╗██╔══██╗╚════██║
Aug 11 22:29:33 Yes-BBS python3[528]:    ██║   ╚██████╗███████╗      ██████╔╝██████╔╝███████║
Aug 11 22:29:33 Yes-BBS python3[528]:    ╚═╝    ╚═════╝╚══════╝      ╚═════╝ ╚═════╝ ╚══════╝
Aug 11 22:29:33 Yes-BBS python3[528]: Meshtastic Version
Aug 11 22:29:33 Yes-BBS python3[528]: Configured to sync with the following BBS nodes: ['!17d7e4b7', '!18e9f5a3', '!1a2b3c4d']
Aug 11 22:29:33 Yes-BBS python3[528]: Nodes with Urgent board permissions: ['!17d7e4b7', '!25064508', '!f72493b8']
Aug 11 22:29:33 Yes-BBS python3[528]: PermissionError: [Errno 13] Permission denied: '/dev/ttyACM0'. Retrying in 5 seconds...
Aug 11 22:29:33 Yes-BBS python3[528]: Traceback (most recent call last):
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/server.py", line 93, in <module>
Aug 11 22:29:33 Yes-BBS python3[528]:     main()
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/server.py", line 62, in main
Aug 11 22:29:33 Yes-BBS python3[528]:     interface = get_interface(system_config)
Aug 11 22:29:33 Yes-BBS python3[528]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/config_init.py", line 161, in get_interface
Aug 11 22:29:33 Yes-BBS python3[528]:     return meshtastic.serial_interface.SerialInterface(system_config['port'])
Aug 11 22:29:33 Yes-BBS python3[528]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/serial_interface.py", line 64, in __init__
Aug 11 22:29:33 Yes-BBS python3[528]:     StreamInterface.__init__(
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 50, in __init__
Aug 11 22:29:33 Yes-BBS python3[528]:     self.connect()
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 74, in connect
Aug 11 22:29:33 Yes-BBS python3[528]:     self._waitConnected()
Aug 11 22:29:33 Yes-BBS python3[528]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 704, in _waitConnected
Aug 11 22:29:33 Yes-BBS python3[528]:     raise MeshInterface.MeshInterfaceError("Timed out waiting for connection completion")
Aug 11 22:29:33 Yes-BBS python3[528]: meshtastic.mesh_interface.MeshInterface.MeshInterfaceError: Timed out waiting for connection completion
Aug 11 22:29:34 Yes-BBS systemd[1]: mesh-bbs.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 22:29:34 Yes-BBS systemd[1]: mesh-bbs.service: Failed with result 'exit-code'.
Aug 11 22:29:34 Yes-BBS systemd[1]: mesh-bbs.service: Consumed 12.729s CPU time.
Aug 11 22:30:24 Yes-BBS systemd[1]: mesh-bbs.service: Scheduled restart job, restart counter is at 1.
Aug 11 22:30:24 Yes-BBS systemd[1]: Stopped mesh-bbs.service - TC²-BBS Meshtastic Version.
Aug 11 22:30:24 Yes-BBS systemd[1]: mesh-bbs.service: Consumed 12.729s CPU time.
Aug 11 22:30:24 Yes-BBS systemd[1]: Started mesh-bbs.service - TC²-BBS Meshtastic Version.
Aug 11 22:30:39 Yes-BBS python3[691]: 2024-08-11 22:30:39 - INFO - TC²-BBS is running on serial interface...
Aug 11 22:30:39 Yes-BBS python3[691]: 2024-08-11 22:30:39 - JS8Call - INFO - JS8Call configuration not found. Skipping JS8Call integration.
Aug 11 22:30:39 Yes-BBS python3[691]: 2024-08-11 22:30:39 - ERROR - Error while handling message from radio Error parsing message
Aug 11 22:30:39 Yes-BBS python3[691]: Traceback (most recent call last):
Aug 11 22:30:39 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 173, in __reader
Aug 11 22:30:39 Yes-BBS python3[691]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
Aug 11 22:30:39 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 875, in _handleFromRadio
Aug 11 22:30:39 Yes-BBS python3[691]:     fromRadio.ParseFromString(fromRadioBytes)
Aug 11 22:30:39 Yes-BBS python3[691]: google.protobuf.message.DecodeError: Error parsing message
Aug 11 22:30:45 Yes-BBS python3[691]: 2024-08-11 22:30:45 - ERROR - Error while handling message from radio Error parsing message
Aug 11 22:30:45 Yes-BBS python3[691]: Traceback (most recent call last):
Aug 11 22:30:45 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 173, in __reader
Aug 11 22:30:45 Yes-BBS python3[691]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
Aug 11 22:30:45 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 875, in _handleFromRadio
Aug 11 22:30:45 Yes-BBS python3[691]:     fromRadio.ParseFromString(fromRadioBytes)
Aug 11 22:30:45 Yes-BBS python3[691]: google.protobuf.message.DecodeError: Error parsing message
Aug 11 22:44:32 Yes-BBS python3[691]: 2024-08-11 22:44:32 - ERROR - Error while handling message from radio Error parsing message
Aug 11 22:44:32 Yes-BBS python3[691]: Traceback (most recent call last):
Aug 11 22:44:32 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/stream_interface.py", line 173, in __reader
Aug 11 22:44:32 Yes-BBS python3[691]:     self._handleFromRadio(self._rxBuf[HEADER_LEN:])
Aug 11 22:44:32 Yes-BBS python3[691]:   File "/home/user/TC2-BBS-mesh/venv/lib/python3.11/site-packages/meshtastic/mesh_interface.py", line 875, in _handleFromRadio
Aug 11 22:44:32 Yes-BBS python3[691]:     fromRadio.ParseFromString(fromRadioBytes)
Aug 11 22:44:32 Yes-BBS python3[691]: google.protobuf.message.DecodeError: Error parsing message

**Comment by SpeedGP** [comment]
Once again, nevermind. I think when I added my wifi card into my rpi (OG), it added another serial port and at some point it changed from ttyAMA0 to ttyACM0

thanks again for the project! Really loving it! Everyone I tell about it asks when the games are coming (Something dragon or something?
