### ISSUE TITLE
KeyError(key)

### ISSUE THREAD

**Issue by ronnietucker** [TheCommsChannel/TC2-BBS-mesh#81]
Just did a
`git pull`
and when trying to run the server I get:
```
Traceback (most recent call last):
  File "/home/ronnie/TC2-BBS-mesh/server.py", line 20, in <module>
    from js8call_integration import JS8CallClient
  File "/home/ronnie/TC2-BBS-mesh/js8call_integration.py", line 10, in <module>
    from command_handlers import handle_help_command
  File "/home/ronnie/TC2-BBS-mesh/command_handlers.py", line 24, in <module>
    main_menu_items = config['menu']['main_menu_items'].split(',')
                      ~~~~~~^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'menu'
```

**Comment by TheCommsChannel** [comment]
A new menu section was added to the config file. You'll need to update your config file 

`mv example_config.ini config.ini`
(you may want to rename your original config file for reference before doing this if needed)
