### ISSUE TITLE
Reading mail - menu control

### ISSUE THREAD

**Issue by ajbrickhouse** [TheCommsChannel/TC2-BBS-mesh#87]
If a non-integer value is entered after accessing the read menu, an error will be returned.

`2024-09-09 18:15:17 - INFO - Received message from user 'Jay' to BBS1: B
2024-09-09 18:15:17 - INFO - REPLY SEND ID=2514651132
2024-09-09 18:15:22 - INFO - Received message from user 'Jay' to BBS1: M
2024-09-09 18:15:22 - INFO - REPLY SEND ID=2514651133
2024-09-09 18:15:31 - INFO - Received message from user 'Jay' to BBS1: R
2024-09-09 18:15:31 - INFO - REPLY SEND ID=2514651134
2024-09-09 18:15:33 - INFO - REPLY SEND ID=2514651135
2024-09-09 18:15:38 - INFO - Received message from user 'Jay' to BBS1: S
2024-09-09 18:15:38 - ERROR - Unexpected error in deferred execution <class 'ValueError'>
Traceback (most recent call last):
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1285, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "/home/tbrinkhuis/TC2-BBS-mesh/venv/lib/python3.10/site-packages/pubsub/core/listener.py", line 237, in __call__
    cb(**kwargs)
  File "/home/tbrinkhuis/TC2-BBS-mesh/server.py", line 71, in receive_packet
    on_receive(packet, interface)
  File "/home/tbrinkhuis/TC2-BBS-mesh/message_processing.py", line 201, in on_receive
    process_message(sender_id, message_string, interface, is_sync_message=False)
  File "/home/tbrinkhuis/TC2-BBS-mesh/message_processing.py", line 140, in process_message
    handle_mail_steps(sender_id, message, step, state, interface, bbs_nodes)
  File "/home/tbrinkhuis/TC2-BBS-mesh/command_handlers.py", line 255, in handle_mail_steps
    mail_id = int(message)
ValueError: invalid literal for int() with base 10: 's'
`

**Comment by AdvJosh** [comment]
Hey @ajbrickhouse,

I created a pull request with improved error handling in the read bulletin and read mail menus that should resolve this.

https://github.com/TheCommsChannel/TC2-BBS-mesh/pull/122
